(() => {
'use strict';
const APP_VERSION='v0.8.1', STORAGE_KEY='recipeRepositoryData_v080', TABLE='foodie_recipes', BUCKET='foodie_recipe_assets';
const RECIPE_TYPES=['Appetizer','Breakfast','Bread','Dessert','Drink','Main Dish','Side Dish','Sauce','Soup/Stew','Salad','Snack','Camp Food'];
const DIETARY_OPTIONS=['Gluten Free','Vegan','Vegetarian','Dairy Free','Low Carb'];
const PRESET_CUISINES=['American','Cajun/Creole','Chinese','French','German','Greek','Indian','Italian','Japanese','Korean','Mediterranean','Mexican','Middle Eastern','Nordic','Spanish','Swedish','Tex-Mex','Thai','Vietnamese'];
const INGREDIENT_CANONICALS={'green onion':['scallion','scallions','green onions','spring onion','spring onions'],'bell pepper':['sweet pepper','sweet peppers','bell peppers','capsicum'],'cilantro':['coriander leaves','fresh coriander'],'zucchini':['courgette','courgettes'],'eggplant':['aubergine','aubergines'],'garbanzo bean':['chickpea','chickpeas','garbanzo beans'],'confectioners sugar':['powdered sugar','icing sugar'],'heavy cream':['double cream','whipping cream'],'cornstarch':['corn flour'],'ground beef':['hamburger','minced beef'],'shrimp':['prawn','prawns'],'arugula':['rocket'],'green bean':['haricots verts','green beans'],'parmesan':['parmigiano reggiano'],'red pepper flake':['crushed red pepper','crushed red pepper flakes','red pepper flakes']};
const PANTRY_STAPLES=new Set(['salt','pepper','black pepper','water','olive oil','vegetable oil','butter','garlic powder','onion powder','flour','sugar']);
const els={}, state={recipes:[],selectedId:null,currentPage:'homePage',loadedFrom:'local browser storage',ingredientTerms:[],supabase:null,filters:{search:'',type:'',cuisine:'',collection:'',tag:'',minRating:'',dietary:[],includeIngredients:'',excludeIngredients:'',ingredientMode:'all',ignoreStaples:true,favoritesOnly:false,duplicatesOnly:false,recentOnly:false},draft:{featuredFile:null,sourceFiles:[],featuredExisting:'',sourceExisting:[]}};
let aliasMap=null;
document.addEventListener('DOMContentLoaded', init);
function $(id){return document.getElementById(id)}
function init(){cacheEls(); initStaticUi(); bindEvents(); routeFromHash(); window.addEventListener('hashchange', routeFromHash); connectSupabase(); loadRecipes().then(()=>{refreshAll(); setStatus(`Ready. Loaded ${state.recipes.length} recipes from ${state.loadedFrom}.`,'success');}).catch(err=>{console.error(err); loadLocalRecipesSync(); refreshAll(); setStatus('Loaded local data after a startup problem.','error');});}
function cacheEls(){['statusText','homeSearchInput','homeSearchBtn','newRecipeBtn','homeFavoritesBtn','homeRecentBtn','quickOpenBrowseBtn','homeStats','homeTypeButtons','homeCuisineButtons','homeDietaryButtons','searchInput','typeFilter','cuisineFilter','collectionFilter','tagFilter','ratingFilter','includeIngredients','excludeIngredients','ingredientMode','ignoreStaples','dietaryOptions','dietaryFilterOptions','favoritesOnlyBtn','duplicatesBtn','recentBtn','clearFiltersBtn','recipeCount','recipeList','recipeDetail','recipeCardTemplate','exportBtn','importFile','printBtn','printIndexCardBtn','deleteBtn','goToEditBtn','runOcrBtn','importFromUrlBtn','saveRecipeBtn','title','recipeType','cuisine','collection','sourceType','sourceLabel','recipeUrl','tags','rating','isFavorite','prepTime','cookTime','recipeYield','featuredImageFile','sourceImageFiles','featuredImagePreview','featuredImageEmpty','sourceImageGallery','ocrText','ingredients','instructions','notes'].forEach(id=>els[id]=$(id)); els.pageTabs=[...document.querySelectorAll('.page-tab')]; els.appPages=[...document.querySelectorAll('.app-page')]; }
function initStaticUi(){document.body.dataset.appVersion=APP_VERSION; fillSelect(els.recipeType, RECIPE_TYPES, 'Choose type'); fillSelect(els.typeFilter, RECIPE_TYPES, 'All types'); renderCheckGroup(els.dietaryOptions,'dietEdit',DIETARY_OPTIONS); renderCheckGroup(els.dietaryFilterOptions,'dietFilter',DIETARY_OPTIONS); refreshCuisineFilter();}
function fillSelect(select, values, firstLabel){if(!select) return; const current=select.value; select.innerHTML=`<option value="">${firstLabel}</option>`; values.forEach(v=>{const o=document.createElement('option'); o.value=v; o.textContent=v; select.appendChild(o);}); if(values.includes(current)) select.value=current;}
function renderCheckGroup(container,prefix,values){if(!container) return; container.innerHTML=''; values.forEach(v=>{const label=document.createElement('label'); label.className='chip-check'; const input=document.createElement('input'); input.type='checkbox'; input.id=`${prefix}-${slugify(v)}`; input.value=v; const span=document.createElement('span'); span.textContent=v; label.append(input,span); container.appendChild(label);});}
function bindEvents(){els.pageTabs.forEach(tab=>tab.addEventListener('click',()=>routeTo(tab.dataset.page||'homePage'))); bind(els.homeSearchBtn,'click',()=>{state.filters.search=els.homeSearchInput.value.trim(); els.searchInput.value=state.filters.search; state.filters.favoritesOnly=false; state.filters.recentOnly=false; state.filters.duplicatesOnly=false; renderList(); routeTo('browsePage');}); bind(els.newRecipeBtn,'click',()=>{clearForm(); routeTo('editPage'); setStatus('New recipe form ready.','neutral');}); bind(els.homeFavoritesBtn,'click',()=>applyHomePreset({favoritesOnly:true})); bind(els.homeRecentBtn,'click',()=>applyHomePreset({recentOnly:true})); bind(els.quickOpenBrowseBtn,'click',()=>applyHomePreset({}));
[['searchInput','search'],['typeFilter','type'],['cuisineFilter','cuisine'],['collectionFilter','collection'],['tagFilter','tag'],['ratingFilter','minRating'],['ingredientMode','ingredientMode']].forEach(([id,key])=>bind(els[id],id.includes('Filter')&&id!=='searchInput'?'change':'input',()=>{state.filters[key]=els[id].value.trim?els[id].value.trim():els[id].value; renderList();}));
bind(els.ignoreStaples,'change',()=>{state.filters.ignoreStaples=!!els.ignoreStaples.checked; renderList();}); bind(els.dietaryFilterOptions,'change',()=>{state.filters.dietary=getCheckedValues(els.dietaryFilterOptions); renderList();}); bind(els.favoritesOnlyBtn,'click',()=>{state.filters.favoritesOnly=!state.filters.favoritesOnly; renderList();}); bind(els.duplicatesBtn,'click',()=>{state.filters.duplicatesOnly=!state.filters.duplicatesOnly; renderList();}); bind(els.recentBtn,'click',()=>{state.filters.recentOnly=!state.filters.recentOnly; renderList();}); bind(els.clearFiltersBtn,'click',clearFilters); bind(els.featuredImageFile,'change',e=>{state.draft.featuredFile=e.target.files?.[0]||null; renderFormPreviews();}); bind(els.sourceImageFiles,'change',e=>{state.draft.sourceFiles=[...(e.target.files||[])]; renderFormPreviews();}); bind(els.runOcrBtn,'click',runOcrOnSourcePages); bind(els.importFromUrlBtn,'click',importFromUrl); bind(els.saveRecipeBtn,'click',saveRecipe); bind(els.exportBtn,'click',exportJson); bind(els.importFile,'change',importJson); bind(els.goToEditBtn,'click',editSelectedRecipe); bind(els.printBtn,'click',()=>printSelected('full')); bind(els.printIndexCardBtn,'click',()=>printSelected('card')); bind(els.deleteBtn,'click',deleteSelectedRecipe); bind(els.includeIngredients,'input',()=>{state.filters.includeIngredients=els.includeIngredients.value; renderSuggestions('include'); renderList();}); bind(els.excludeIngredients,'input',()=>{state.filters.excludeIngredients=els.excludeIngredients.value; renderSuggestions('exclude'); renderList();}); bindSuggestionBox('include'); bindSuggestionBox('exclude'); document.addEventListener('click',e=>{if(!e.target.closest('.suggestion-box')&&e.target!==els.includeIngredients&&e.target!==els.excludeIngredients){hideSuggestions('include'); hideSuggestions('exclude');}}); }
function bind(el,ev,fn){if(el) el.addEventListener(ev,fn)}
function connectSupabase(){const cfg=window.RECIPE_APP_CONFIG||{}; if(window.supabase&&cfg.supabaseUrl&&cfg.supabaseAnonKey) state.supabase=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);}
async function loadRecipes(){ if(!state.supabase){loadLocalRecipesSync(); return;} const {data,error}=await state.supabase.from(TABLE).select('*').order('updated_at',{ascending:false}); if(error){console.error('Supabase load failed',error); loadLocalRecipesSync(); setStatus('Supabase load failed; using local data.','error'); return;} state.recipes=(data||[]).map(normalizeRecipe); state.loadedFrom='Supabase'; persistLocal(); }
function loadLocalRecipesSync(){const raw=localStorage.getItem(STORAGE_KEY); let parsed=[]; try{parsed=raw?JSON.parse(raw):[]}catch{} state.recipes=Array.isArray(parsed)?parsed.map(normalizeRecipe):[]; state.loadedFrom='local browser storage';}
function persistLocal(){localStorage.setItem(STORAGE_KEY, JSON.stringify(state.recipes));}
function normalizeRecipe(r={}){const x={...r}; x.id=x.id||crypto.randomUUID(); x.title=str(x.title); x.recipe_type=str(x.recipe_type||x.category); x.cuisine=str(x.cuisine); x.collection=str(x.collection); x.source_type=str(x.source_type||'manual'); x.source_label=str(x.source_label); x.recipe_url=str(x.recipe_url); x.tags=Array.isArray(x.tags)?x.tags.map(str).filter(Boolean):csvToArray(x.tags); x.dietary=Array.isArray(x.dietary)?x.dietary.map(str).filter(Boolean):csvToArray(x.dietary); x.ingredients=str(x.ingredients); x.instructions=str(x.instructions); x.notes=str(x.notes); x.ocr_text=str(x.ocr_text); x.featured_image_url=str(x.featured_image_url||x.image_url); x.source_image_urls=Array.isArray(x.source_image_urls)?x.source_image_urls.filter(Boolean):[]; x.rating=x.rating?Number(x.rating):null; x.is_favorite=!!x.is_favorite; x.prep_time=str(x.prep_time); x.cook_time=str(x.cook_time); x.recipe_yield=str(x.recipe_yield); x.created_at=x.created_at||new Date().toISOString(); x.updated_at=x.updated_at||x.created_at; return x; }
function refreshAll(){refreshCuisineFilter(); buildIngredientIndex(); renderHomePage(); renderList(); renderFormPreviews();}
function refreshCuisineFilter(){const all=[...new Set([...PRESET_CUISINES,...state.recipes.map(r=>r.cuisine).filter(Boolean)])].sort((a,b)=>a.localeCompare(b)); fillSelect(els.cuisineFilter, all, 'All cuisines');}
function renderHomePage(){if(els.homeStats){const favoriteCount=state.recipes.filter(r=>r.is_favorite).length; const cuisineCount=state.recipes.filter(r=>r.cuisine).length; const photoCount=state.recipes.filter(r=>r.featured_image_url||(r.source_image_urls||[]).length).length; els.homeStats.innerHTML=[statCard('Recipes',state.recipes.length),statCard('Favorites',favoriteCount),statCard('With cuisine',cuisineCount),statCard('With photos',photoCount)].join('');}
if(els.homeTypeButtons){els.homeTypeButtons.innerHTML=RECIPE_TYPES.map(type=>jumpBtn(type,state.recipes.filter(r=>r.recipe_type===type).length,`data-home-type="${esc(type)}"`)).join(''); [...els.homeTypeButtons.querySelectorAll('[data-home-type]')].forEach(b=>b.addEventListener('click',()=>applyHomePreset({type:b.dataset.homeType})));}
const cuisines=[...new Set([...PRESET_CUISINES,...state.recipes.map(r=>r.cuisine).filter(Boolean)])].slice(0,24); if(els.homeCuisineButtons){els.homeCuisineButtons.innerHTML=cuisines.map(c=>jumpBtn(c,state.recipes.filter(r=>r.cuisine===c).length,`data-home-cuisine="${esc(c)}"`)).join(''); [...els.homeCuisineButtons.querySelectorAll('[data-home-cuisine]')].forEach(b=>b.addEventListener('click',()=>applyHomePreset({cuisine:b.dataset.homeCuisine})));}
if(els.homeDietaryButtons){els.homeDietaryButtons.innerHTML=DIETARY_OPTIONS.map(d=>jumpBtn(d,state.recipes.filter(r=>r.dietary.includes(d)).length,`data-home-dietary="${esc(d)}"`)).join(''); [...els.homeDietaryButtons.querySelectorAll('[data-home-dietary]')].forEach(b=>b.addEventListener('click',()=>applyHomePreset({dietary:[b.dataset.homeDietary]})));}}
function statCard(label,val){return `<div class="stat-card"><div class="stat-value">${esc(String(val))}</div><div class="stat-label">${esc(label)}</div></div>`}
function jumpBtn(label,count,attrs){return `<button type="button" class="jump-button" ${attrs}><span>${esc(label)}</span><small>${count}</small></button>`}
function applyHomePreset({search='',type='',cuisine='',dietary=[],favoritesOnly=false,recentOnly=false}={}){state.filters={search,type,cuisine,collection:'',tag:'',minRating:'',dietary,includeIngredients:'',excludeIngredients:'',ingredientMode:'all',ignoreStaples:true,favoritesOnly,duplicatesOnly:false,recentOnly}; els.searchInput.value=search; els.typeFilter.value=type; els.cuisineFilter.value=cuisine; els.collectionFilter.value=''; els.tagFilter.value=''; els.ratingFilter.value=''; els.includeIngredients.value=''; els.excludeIngredients.value=''; els.ingredientMode.value='all'; els.ignoreStaples.checked=true; setCheckedValues(els.dietaryFilterOptions,dietary); renderList(); routeTo('browsePage');}
function renderList(){const list=filterRecipes(); toggleClass(els.favoritesOnlyBtn,'is-on',state.filters.favoritesOnly); toggleClass(els.duplicatesBtn,'is-on',state.filters.duplicatesOnly); toggleClass(els.recentBtn,'is-on',state.filters.recentOnly); els.recipeCount.textContent=`${list.length} recipe${list.length===1?'':'s'}`; els.recipeList.innerHTML=''; if(!list.length){els.recipeList.innerHTML='<div class="empty-state"><p>No recipes match this filter set.</p></div>'; renderDetail(null); return;} list.forEach(recipe=>{const node=els.recipeCardTemplate.content.firstElementChild.cloneNode(true); node.dataset.recipeId=recipe.id; node.querySelector('.recipe-card-title').textContent=recipe.title||'Untitled recipe'; node.querySelector('.recipe-card-subline').textContent=[recipe.recipe_type,recipe.cuisine,recipe.collection].filter(Boolean).join(' • '); node.querySelector('.recipe-card-rating').textContent=recipe.rating?`${recipe.rating}/5`:''; const img=node.querySelector('.recipe-card-image'); if(recipe.featured_image_url){img.src=recipe.featured_image_url; img.hidden=false;} node.querySelector('.recipe-card-match').textContent=buildMatchText(recipe); node.querySelector('.recipe-card-tags').textContent=[...recipe.dietary,...recipe.tags].slice(0,6).join(' • '); node.addEventListener('click',()=>selectRecipe(recipe.id)); els.recipeList.appendChild(node);}); if(!list.some(r=>r.id===state.selectedId)) state.selectedId=list[0].id; renderDetail(state.recipes.find(r=>r.id===state.selectedId)||list[0]);}
function filterRecipes(){const dupes=duplicateTitleSet(); return state.recipes.filter(recipe=>{const search=state.filters.search.toLowerCase(); if(search){const hay=[recipe.title,recipe.collection,recipe.cuisine,recipe.ingredients,recipe.instructions,recipe.notes,recipe.ocr_text,recipe.source_label,recipe.recipe_url,recipe.tags.join(' '),recipe.dietary.join(' ')].join(' ').toLowerCase(); if(!hay.includes(search)) return false;} if(state.filters.type&&recipe.recipe_type!==state.filters.type) return false; if(state.filters.cuisine&&recipe.cuisine!==state.filters.cuisine) return false; if(state.filters.collection&&!recipe.collection.toLowerCase().includes(state.filters.collection.toLowerCase())) return false; if(state.filters.tag&&!recipe.tags.join(' ').toLowerCase().includes(state.filters.tag.toLowerCase())) return false; if(state.filters.minRating&&(!recipe.rating||recipe.rating<Number(state.filters.minRating))) return false; if(state.filters.favoritesOnly&&!recipe.is_favorite) return false; if(state.filters.duplicatesOnly&&!dupes.has(normalizeTitle(recipe.title))) return false; if(state.filters.recentOnly&&((Date.now()-new Date(recipe.updated_at).getTime())/86400000>14)) return false; if(state.filters.dietary.length&&!state.filters.dietary.every(d=>recipe.dietary.includes(d))) return false; if(!passesIngredientFilter(recipe)) return false; return true;}).sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at));}
function duplicateTitleSet(){const m=new Map(); state.recipes.forEach(r=>{const key=normalizeTitle(r.title); if(key) m.set(key,(m.get(key)||0)+1)}); return new Set([...m].filter(([,c])=>c>1).map(([k])=>k));}
function passesIngredientFilter(recipe){const include=splitIngredientTerms(state.filters.includeIngredients,state.filters.ignoreStaples), exclude=splitIngredientTerms(state.filters.excludeIngredients,state.filters.ignoreStaples), terms=recipeIngredientTerms(recipe); if(exclude.some(t=>terms.has(t))) return false; if(!include.length) return true; const matches=include.filter(t=>terms.has(t)).length; return state.filters.ingredientMode==='all'?matches===include.length:state.filters.ingredientMode==='most'?matches>=Math.max(1,Math.ceil(include.length*.6)):matches>=1;}
function buildMatchText(recipe){const include=splitIngredientTerms(state.filters.includeIngredients,state.filters.ignoreStaples); if(!include.length) return recipe.recipe_yield||''; const terms=recipeIngredientTerms(recipe), matches=include.filter(t=>terms.has(t)), missing=include.filter(t=>!terms.has(t)); return `${matches.length}/${include.length} ingredients matched${missing.length?` • missing: ${missing.join(', ')}`:''}`;}
function recipeIngredientTerms(recipe){return new Set(String(recipe.ingredients||'').split(/\n|,/).map(normalizeIngredientPhrase).filter(Boolean));}
function selectRecipe(id){state.selectedId=id; renderDetail(state.recipes.find(r=>r.id===id)||null)}
function renderDetail(recipe){if(!recipe){els.recipeDetail.className='recipe-detail empty-state'; els.recipeDetail.innerHTML='<p>Select a recipe.</p>'; return;} els.recipeDetail.className='recipe-detail'; const extras=(recipe.source_image_urls||[]).filter(Boolean); els.recipeDetail.innerHTML=`<div class="detail-hero">${recipe.featured_image_url?`<img class="detail-image" src="${esc(recipe.featured_image_url)}" alt="${esc(recipe.title)}">`:''}<div class="detail-meta"><h3>${esc(recipe.title||'Untitled recipe')}</h3><p class="muted">${esc([recipe.recipe_type,recipe.cuisine,recipe.collection].filter(Boolean).join(' • '))}</p><p>${recipe.is_favorite?'★ Favorite ':''}${recipe.rating?`${recipe.rating}/5`:''}</p><p>${esc(recipe.recipe_yield||'')}</p><p>${esc(recipe.prep_time?`Prep: ${recipe.prep_time}`:'')}${recipe.cook_time?`  Cook: ${recipe.cook_time}`:''}</p><p>${esc(recipe.source_label||'')}</p>${recipe.recipe_url?`<p><a href="${esc(recipe.recipe_url)}" target="_blank" rel="noopener">Open source link</a></p>`:''}</div></div>${recipe.dietary.length?`<p><strong>Dietary:</strong> ${esc(recipe.dietary.join(', '))}</p>`:''}${recipe.tags.length?`<p><strong>Tags:</strong> ${esc(recipe.tags.join(', '))}</p>`:''}<div class="two-col stackable"><section><h4>Ingredients</h4><pre>${esc(recipe.ingredients)}</pre></section><section><h4>Instructions</h4><pre>${esc(recipe.instructions)}</pre></section></div>${recipe.notes?`<section><h4>Notes</h4><pre>${esc(recipe.notes)}</pre></section>`:''}${recipe.ocr_text?`<details><summary>OCR / Imported Text</summary><pre>${esc(recipe.ocr_text)}</pre></details>`:''}${extras.length?`<section><h4>Extra Images</h4><div class="source-gallery">${extras.map(url=>`<div class="source-image-card"><img src="${esc(url)}" alt=""></div>`).join('')}</div></section>`:''}`;}
function editSelectedRecipe(){const recipe=state.recipes.find(r=>r.id===state.selectedId); if(!recipe) return; populateForm(recipe); routeTo('editPage');}
function clearForm(){['title','cuisine','collection','sourceLabel','recipeUrl','tags','prepTime','cookTime','recipeYield','ocrText','ingredients','instructions','notes'].forEach(id=>{els[id].value=''}); els.recipeType.value=''; els.sourceType.value='manual'; els.rating.value=''; els.isFavorite.checked=false; setCheckedValues(els.dietaryOptions,[]); state.selectedId=null; state.draft={featuredFile:null,sourceFiles:[],featuredExisting:'',sourceExisting:[]}; if(els.featuredImageFile) els.featuredImageFile.value=''; if(els.sourceImageFiles) els.sourceImageFiles.value=''; renderFormPreviews();}
function populateForm(recipe){els.title.value=recipe.title||''; els.recipeType.value=recipe.recipe_type||''; els.cuisine.value=recipe.cuisine||''; els.collection.value=recipe.collection||''; els.sourceType.value=recipe.source_type||'manual'; els.sourceLabel.value=recipe.source_label||''; els.recipeUrl.value=recipe.recipe_url||''; els.tags.value=recipe.tags.join(', '); els.rating.value=recipe.rating||''; els.isFavorite.checked=!!recipe.is_favorite; els.prepTime.value=recipe.prep_time||''; els.cookTime.value=recipe.cook_time||''; els.recipeYield.value=recipe.recipe_yield||''; els.ocrText.value=recipe.ocr_text||''; els.ingredients.value=recipe.ingredients||''; els.instructions.value=recipe.instructions||''; els.notes.value=recipe.notes||''; setCheckedValues(els.dietaryOptions, recipe.dietary||[]); state.selectedId=recipe.id; state.draft={featuredFile:null,sourceFiles:[],featuredExisting:recipe.featured_image_url||'',sourceExisting:[...(recipe.source_image_urls||[])]}; renderFormPreviews();}
function renderFormPreviews(){const featured=state.draft.featuredFile?URL.createObjectURL(state.draft.featuredFile):state.draft.featuredExisting; if(featured){els.featuredImagePreview.src=featured; els.featuredImagePreview.hidden=false; els.featuredImageEmpty.hidden=true;} else {els.featuredImagePreview.hidden=true; els.featuredImagePreview.removeAttribute('src'); els.featuredImageEmpty.hidden=false;} const items=[]; state.draft.sourceExisting.forEach((url,i)=>items.push({kind:'existing',index:i,url})); state.draft.sourceFiles.forEach((f,i)=>items.push({kind:'file',index:i,url:URL.createObjectURL(f)})); els.sourceImageGallery.innerHTML=''; if(!items.length){els.sourceImageGallery.innerHTML='<div class="image-empty">No source pages or extra photos selected yet.</div>'; return;} items.forEach(item=>{const card=document.createElement('div'); card.className='source-image-card'; card.innerHTML=`<img src="${esc(item.url)}" alt="Source image"><div class="source-image-actions"><button type="button" data-set-featured="${item.kind}:${item.index}">Set as featured</button><button type="button" data-remove-source="${item.kind}:${item.index}">Remove</button></div>`; els.sourceImageGallery.appendChild(card);}); [...els.sourceImageGallery.querySelectorAll('[data-set-featured]')].forEach(btn=>btn.addEventListener('click',setSourceAsFeatured)); [...els.sourceImageGallery.querySelectorAll('[data-remove-source]')].forEach(btn=>btn.addEventListener('click',removeSourceImage));}
function setSourceAsFeatured(e){const [kind,idx]=String(e.currentTarget.dataset.setFeatured||'').split(':'); const i=Number(idx); if(kind==='existing'){state.draft.featuredExisting=state.draft.sourceExisting[i]||''; state.draft.featuredFile=null;} else {state.draft.featuredFile=state.draft.sourceFiles[i]||null; state.draft.featuredExisting='';} renderFormPreviews();}
function removeSourceImage(e){const [kind,idx]=String(e.currentTarget.dataset.removeSource||'').split(':'); const i=Number(idx); if(kind==='existing') state.draft.sourceExisting.splice(i,1); else state.draft.sourceFiles.splice(i,1); renderFormPreviews();}
async function runOcrOnSourcePages(){const files=state.draft.sourceFiles.length?state.draft.sourceFiles:(state.draft.featuredFile?[state.draft.featuredFile]:[]); if(!files.length){setStatus('Add one or more source images first.','error'); return;} if(!window.Tesseract){setStatus('Tesseract OCR is not available.','error'); return;} setStatus('Running OCR…','neutral'); const chunks=[]; for(let i=0;i<files.length;i++){const result=await window.Tesseract.recognize(files[i],'eng'); chunks.push(`--- Page ${i+1} ---\n${(result.data.text||'').trim()}`);} els.ocrText.value=chunks.join('\n\n'); if(!els.ingredients.value&&!els.instructions.value){const parsed=roughParseOcr(els.ocrText.value); if(parsed.title&&!els.title.value) els.title.value=parsed.title; els.ingredients.value=parsed.ingredients; els.instructions.value=parsed.instructions; mergeTags(parsed.tags);} setStatus('OCR finished. Review and correct it.','success');}
function roughParseOcr(text){const clean=String(text||'').trim(), lines=clean.split(/\n+/).map(s=>s.trim()).filter(Boolean), lower=clean.toLowerCase(); const title=lines[0]||''; const ing=lower.indexOf('ingredients'), ins=Math.max(lower.indexOf('instructions'),lower.indexOf('directions'),lower.indexOf('method')); let ingredients='', instructions=''; if(ing>=0&&ins>ing){ingredients=clean.slice(ing,ins).replace(/^ingredients[:\s]*/i,'').trim(); instructions=clean.slice(ins).replace(/^(instructions|directions|method)[:\s]*/i,'').trim();} else {const mid=Math.ceil(lines.length/2); ingredients=lines.slice(1,mid).join('\n'); instructions=lines.slice(mid).join('\n');} const tags=[]; if(/gluten\s*free/i.test(clean)) tags.push('Gluten Free'); if(/vegan/i.test(clean)) tags.push('Vegan'); if(/vegetarian/i.test(clean)) tags.push('Vegetarian'); return {title,ingredients,instructions,tags};}
async function importFromUrl(){const url=els.recipeUrl.value.trim(); if(!url){setStatus('Paste a recipe URL first.','error'); return;} setStatus('Trying URL import…','neutral'); try{const html=await fetchRecipeHtml(url); const parsed=parseRecipeHtml(html,url); if(parsed.title&&!els.title.value) els.title.value=parsed.title; if(parsed.ingredients&&!els.ingredients.value) els.ingredients.value=parsed.ingredients; if(parsed.instructions&&!els.instructions.value) els.instructions.value=parsed.instructions; if(parsed.recipeYield&&!els.recipeYield.value) els.recipeYield.value=parsed.recipeYield; if(parsed.cuisine&&!els.cuisine.value) els.cuisine.value=parsed.cuisine; if(parsed.ocrText) els.ocrText.value=parsed.ocrText; mergeTags(parsed.tags||[]); setStatus('URL import finished. Review before saving.','success');}catch(err){console.error(err); setStatus('URL import failed. Many sites block browser fetches. Try a screenshot + OCR for stubborn sites.','error');}}
async function fetchRecipeHtml(url){try{const resp=await fetch(url,{mode:'cors'}); if(!resp.ok) throw new Error(`Direct fetch failed: ${resp.status}`); return await resp.text();}catch(firstErr){const proxyUrl=`https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`; const resp=await fetch(proxyUrl); if(!resp.ok) throw firstErr; return await resp.text();}}
function parseRecipeHtml(html,sourceUrl){const doc=new DOMParser().parseFromString(html,'text/html'); const scripts=[...doc.querySelectorAll('script[type="application/ld+json"]')]; const out={title:'',ingredients:'',instructions:'',recipeYield:'',cuisine:'',tags:[],ocrText:''}; for(const script of scripts){try{const raw=JSON.parse(script.textContent), items=Array.isArray(raw)?raw:[raw]; for(const item of items.flatMap(x=>Array.isArray(x?.['@graph'])?x['@graph']:[x])){if(String(item?.['@type']||'').toLowerCase().includes('recipe')){out.title=item.name||out.title; out.ingredients=Array.isArray(item.recipeIngredient)?item.recipeIngredient.join('\n'):out.ingredients; out.instructions=extractInstructions(item.recipeInstructions)||out.instructions; out.recipeYield=Array.isArray(item.recipeYield)?item.recipeYield.join(', '):(item.recipeYield||out.recipeYield); out.cuisine=item.recipeCuisine||out.cuisine; out.ocrText=[out.title,out.ingredients,out.instructions].filter(Boolean).join('\n\n'); return out;}}}catch{}}
out.title=str(doc.querySelector('h1')?.textContent||doc.title||sourceUrl); out.ocrText=[...doc.querySelectorAll('p,li')].slice(0,80).map(n=>n.textContent.trim()).filter(Boolean).join('\n'); return out;}
function extractInstructions(val){if(!val) return ''; if(typeof val==='string') return val; if(Array.isArray(val)) return val.map(v=>typeof v==='string'?v:(v.text||'')).filter(Boolean).join('\n'); if(typeof val==='object') return val.text||''; return '';}
async function saveRecipe(){const recipe=recipeFromForm(); if(!recipe.title){setStatus('Title is required.','error'); return;} setStatus('Saving recipe…','neutral'); try{if(state.supabase){const uploads=await uploadImages(recipe.id); recipe.featured_image_url=uploads.featured||state.draft.featuredExisting||''; recipe.source_image_urls=[...state.draft.sourceExisting,...uploads.sources]; const payload=toPayload(recipe); const {data,error}=await state.supabase.from(TABLE).upsert(payload).select().single(); if(error) throw error; upsertRecipe(normalizeRecipe(data)); state.loadedFrom='Supabase';} else {const embeds=await localEmbedImages(); recipe.featured_image_url=embeds.featured||state.draft.featuredExisting||''; recipe.source_image_urls=[...state.draft.sourceExisting,...embeds.sources]; upsertRecipe(recipe);} persistLocal(); refreshAll(); state.selectedId=recipe.id; renderDetail(state.recipes.find(r=>r.id===recipe.id)); routeTo('browsePage'); setStatus('Recipe saved.','success');}catch(err){console.error(err); setStatus('Save failed. Check the console.','error');}}
function recipeFromForm(){const existing=state.recipes.find(r=>r.id===state.selectedId), id=existing?.id||crypto.randomUUID(); return normalizeRecipe({...existing,id,title:els.title.value.trim(),recipe_type:els.recipeType.value,cuisine:els.cuisine.value.trim(),collection:els.collection.value.trim(),source_type:els.sourceType.value,source_label:els.sourceLabel.value.trim(),recipe_url:els.recipeUrl.value.trim(),tags:csvToArray(els.tags.value),dietary:getCheckedValues(els.dietaryOptions),rating:els.rating.value?Number(els.rating.value):null,is_favorite:!!els.isFavorite.checked,prep_time:els.prepTime.value.trim(),cook_time:els.cookTime.value.trim(),recipe_yield:els.recipeYield.value.trim(),ocr_text:els.ocrText.value,ingredients:els.ingredients.value,instructions:els.instructions.value,notes:els.notes.value,updated_at:new Date().toISOString(),created_at:existing?.created_at||new Date().toISOString()});}
async function uploadImages(recipeId){const out={featured:'',sources:[]}, bucket=(window.RECIPE_APP_CONFIG||{}).storageBucket||BUCKET; if(state.draft.featuredFile) out.featured=await uploadFile(state.draft.featuredFile,recipeId,bucket,'featured'); for(const file of state.draft.sourceFiles) out.sources.push(await uploadFile(file,recipeId,bucket,'source')); return out;}
async function uploadFile(file,recipeId,bucket,kind){const ext=(file.name.split('.').pop()||'jpg').toLowerCase(), path=`${recipeId}/${kind}-${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`; const {error}=await state.supabase.storage.from(bucket).upload(path,file,{upsert:true}); if(error) throw error; const {data}=state.supabase.storage.from(bucket).getPublicUrl(path); return data?.publicUrl||'';}
async function localEmbedImages(){const out={featured:'',sources:[]}; if(state.draft.featuredFile) out.featured=await fileToDataURL(state.draft.featuredFile); for(const file of state.draft.sourceFiles) out.sources.push(await fileToDataURL(file)); return out;}
function toPayload(r){return {id:r.id,title:r.title,recipe_type:r.recipe_type,category:r.recipe_type,cuisine:r.cuisine,collection:r.collection,source_type:r.source_type,source_label:r.source_label,recipe_url:r.recipe_url,tags:r.tags,dietary:r.dietary,rating:r.rating,is_favorite:r.is_favorite,prep_time:r.prep_time,cook_time:r.cook_time,recipe_yield:r.recipe_yield,ocr_text:r.ocr_text,ingredients:r.ingredients,instructions:r.instructions,notes:r.notes,featured_image_url:r.featured_image_url,source_image_urls:r.source_image_urls,updated_at:r.updated_at,created_at:r.created_at};}
function upsertRecipe(recipe){const i=state.recipes.findIndex(r=>r.id===recipe.id); if(i>=0) state.recipes[i]=recipe; else state.recipes.unshift(recipe);}
async function deleteSelectedRecipe(){const recipe=state.recipes.find(r=>r.id===state.selectedId); if(!recipe) return; if(!window.confirm(`Delete “${recipe.title}”?`)) return; try{if(state.supabase){const {error}=await state.supabase.from(TABLE).delete().eq('id',recipe.id); if(error) throw error;} state.recipes=state.recipes.filter(r=>r.id!==recipe.id); state.selectedId=null; persistLocal(); refreshAll(); setStatus('Recipe deleted.','success');}catch(err){console.error(err); setStatus('Delete failed.','error');}}
function exportJson(){const blob=new Blob([JSON.stringify(state.recipes,null,2)],{type:'application/json'}), url=URL.createObjectURL(blob), a=document.createElement('a'); a.href=url; a.download=`recipe-repository-export-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(url);}
async function importJson(e){const file=e.target.files?.[0]; if(!file) return; try{const text=await file.text(), parsed=JSON.parse(text); if(!Array.isArray(parsed)) throw new Error('Array required'); parsed.map(normalizeRecipe).forEach(upsertRecipe); persistLocal(); refreshAll(); setStatus('JSON import complete.','success');}catch(err){console.error(err); setStatus('JSON import failed.','error');} finally{e.target.value='';}}
function printSelected(mode){const recipe=state.recipes.find(r=>r.id===state.selectedId); if(!recipe) return; const w=window.open('','_blank'); if(!w) return; const compact=mode==='card'; w.document.write(`<!doctype html><html><head><title>${esc(recipe.title)}</title><style>body{font-family:Arial,sans-serif;padding:${compact?'12px':'24px'};max-width:${compact?'4in':'8.5in'};margin:auto}pre{white-space:pre-wrap;font-family:inherit}img{max-width:100%;height:auto;border-radius:8px}.cols{display:grid;grid-template-columns:${compact?'1fr':'1fr 1fr'};gap:16px}@media print{@page{size:${compact?'4in 6in':'auto'};margin:.4in}}</style></head><body><h1>${esc(recipe.title)}</h1>${recipe.featured_image_url?`<img src="${esc(recipe.featured_image_url)}" alt="">`:''}<p>${esc([recipe.recipe_type,recipe.cuisine,recipe.collection].filter(Boolean).join(' • '))}</p><div class="cols"><section><h2>Ingredients</h2><pre>${esc(recipe.ingredients)}</pre></section><section><h2>Instructions</h2><pre>${esc(recipe.instructions)}</pre></section></div>${recipe.notes?`<section><h2>Notes</h2><pre>${esc(recipe.notes)}</pre></section>`:''}</body></html>`); w.document.close(); w.focus(); w.print();}
function routeFromHash(){routeTo((location.hash||'#homePage').slice(1)||'homePage',true)}
function routeTo(pageId,fromHash=false){const safe=['homePage','browsePage','editPage'].includes(pageId)?pageId:'homePage'; state.currentPage=safe; els.appPages.forEach(p=>p.classList.toggle('is-active',p.id===safe)); els.pageTabs.forEach(t=>t.classList.toggle('is-active',(t.dataset.page||'')===safe)); if(!fromHash&&location.hash!==`#${safe}`) location.hash=safe; window.scrollTo(0,0);}
function clearFilters(){state.filters={search:'',type:'',cuisine:'',collection:'',tag:'',minRating:'',dietary:[],includeIngredients:'',excludeIngredients:'',ingredientMode:'all',ignoreStaples:true,favoritesOnly:false,duplicatesOnly:false,recentOnly:false}; els.searchInput.value=''; els.typeFilter.value=''; els.cuisineFilter.value=''; els.collectionFilter.value=''; els.tagFilter.value=''; els.ratingFilter.value=''; els.includeIngredients.value=''; els.excludeIngredients.value=''; els.ingredientMode.value='all'; els.ignoreStaples.checked=true; setCheckedValues(els.dietaryFilterOptions,[]); hideSuggestions('include'); hideSuggestions('exclude'); renderList();}
function buildIngredientIndex(){const set=new Set(); state.recipes.forEach(r=>recipeIngredientTerms(r).forEach(t=>set.add(t))); state.ingredientTerms=[...set].sort((a,b)=>a.localeCompare(b));}
function bindSuggestionBox(kind){const box=$(kind==='include'?'includeIngredientSuggestions':'excludeIngredientSuggestions'); if(!box) return; box.addEventListener('click',e=>{const btn=e.target.closest('button[data-suggestion]'); if(!btn) return; const input=kind==='include'?els.includeIngredients:els.excludeIngredients; input.value=applySuggestion(input.value,btn.dataset.suggestion); box.hidden=true; state.filters[kind==='include'?'includeIngredients':'excludeIngredients']=input.value; renderList(); input.focus();});}
function renderSuggestions(kind){const input=kind==='include'?els.includeIngredients:els.excludeIngredients, box=$(kind==='include'?'includeIngredientSuggestions':'excludeIngredientSuggestions'); if(!box) return; const term=input.value.split(',').pop().trim().toLowerCase(); if(term.length<2){box.hidden=true; box.innerHTML=''; return;} const matches=state.ingredientTerms.filter(t=>t.includes(term)).slice(0,8); if(!matches.length){box.hidden=true; box.innerHTML=''; return;} box.innerHTML=matches.map(t=>`<button type="button" data-suggestion="${esc(t)}">${esc(t)}</button>`).join(''); box.hidden=false;}
function hideSuggestions(kind){const box=$(kind==='include'?'includeIngredientSuggestions':'excludeIngredientSuggestions'); if(box){box.hidden=true; box.innerHTML='';}}
function applySuggestion(current,suggestion){const bits=current.split(','); bits[bits.length-1]=` ${suggestion}`; return bits.join(',').replace(/^\s+/,'').replace(/,\s+/g,', ').replace(/\s{2,}/g,' ').trim();}
function mergeTags(tags){const tagSet=new Set(csvToArray(els.tags.value)); (tags||[]).forEach(t=>tagSet.add(t)); els.tags.value=[...tagSet].join(', '); const diet=new Set(getCheckedValues(els.dietaryOptions)); (tags||[]).filter(t=>DIETARY_OPTIONS.includes(t)).forEach(t=>diet.add(t)); setCheckedValues(els.dietaryOptions,[...diet]);}
function csvToArray(v){if(!v) return []; if(Array.isArray(v)) return v.map(str).filter(Boolean); return String(v).split(',').map(s=>s.trim()).filter(Boolean)}
function getCheckedValues(container){return [...container.querySelectorAll('input:checked')].map(i=>i.value)}
function setCheckedValues(container,values){const set=new Set(values||[]); container.querySelectorAll('input').forEach(i=>{i.checked=set.has(i.value)})}
function str(v){return String(v||'').trim()}
function slugify(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function normalizeTitle(v){return slugify(v).replace(/-/g,' ')}
function toggleClass(el,name,on){if(el) el.classList.toggle(name,!!on)}
function setStatus(msg,tone='neutral'){if(els.statusText){els.statusText.textContent=msg; els.statusText.dataset.tone=tone}}
function fileToDataURL(file){return new Promise((res,rej)=>{const fr=new FileReader(); fr.onload=()=>res(String(fr.result||'')); fr.onerror=rej; fr.readAsDataURL(file);})}
function getAliasMap(){if(aliasMap) return aliasMap; aliasMap=new Map(); Object.entries(INGREDIENT_CANONICALS).forEach(([canon,aliases])=>{aliasMap.set(basicNormalize(canon),canon); aliases.forEach(a=>aliasMap.set(basicNormalize(a),canon));}); return aliasMap;}
function basicNormalize(v){return String(v||'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9\s-]/g,' ').replace(/\b(fresh|dried|large|small|medium|extra|virgin|optional|divided|chopped|diced|minced|sliced|shredded|grated|crushed|ground|to taste)\b/g,' ').replace(/\s+/g,' ').trim()}
function normalizeIngredientPhrase(v){const n=basicNormalize(v).replace(/\b(onions|peppers|tomatoes|mushrooms|carrots|beans|cloves)\b/g,m=>m.slice(0,-1)); return getAliasMap().get(n)||n}
function splitIngredientTerms(v,ignore){return String(v||'').split(',').map(normalizeIngredientPhrase).filter(Boolean).filter(t=>!ignore||!PANTRY_STAPLES.has(t))}
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
window.__recipeActions={newRecipeBtn:()=>{clearForm(); routeTo('editPage'); setStatus('New recipe form ready.','neutral');},runOcrBtn:()=>runOcrOnSourcePages(),importFromUrlBtn:()=>importFromUrl(),saveRecipeBtn:()=>saveRecipe()};
})();
